### ISSUE TITLE
Enable XML API doc generation

### ISSUE THREAD

**Issue by danroth27** [dotnet/jsinterop#4]
The latest Microsoft.JSInterop and Mono.WebAssembly.Interop packages are missing the XML API doc files. These are needed to generate API docs for these libraries.

**Comment by aspnet-hello** [comment]
We're closing this item because this project has moved to another repo.

Please go to https://github.com/aspnet/Extensions/tree/master/src/JSInterop to see the latest JSInterop code base and to file issues.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
