### ISSUE TITLE
Allow JsInvokable method to have access modifier - internal

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/jsinterop#8]
I do some blazor component and want to host it as nuget package.

Mostly have methods marked as internal because they don't should be visible outside assembly.

Can't set internal to [JSInvokable] method because it requires only public.

I don't want this methods to be public accessible.

![untitled](https://user-images.githubusercontent.com/40779557/53512915-f238fa00-3a91-11e9-8e91-fa6786210091.png)

**Comment by Lupusa87** [comment]
Maybe this has no sense.

In case where we have referenced some blazor lib, js execution happens not in referenced lib but in project where it is added, so maybe there is no way to see/invoke/call referenced component's internal methods.

**Comment by aspnet-hello** [comment]
We're closing this item because this project has moved to another repo.

Please go to https://github.com/aspnet/Extensions/tree/master/src/JSInterop to see the latest JSInterop code base and to file issues.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
